### ISSUE TITLE
`workerId` has incorrect value when `runtime: 'child_process'`

### ISSUE THREAD

**Issue by AriPerkkio** [tinylibs/tinypool#80]
Original report at https://github.com/vitest-dev/vitest/issues/4982.

Tinypool exports `workerId` from public API. When using `runtime: 'child_process'` this variable contains `process.pid` - not the `workerId` that Tinypool has generated.

This bug was introduced in https://github.com/tinylibs/tinypool/pull/65. I thought that `workerId` would be the same as `node:worker_threads.threadId`, but it seems that `pool.threads[number]?.threadId` is actually that.

**Comment by AriPerkkio** [comment]
As `child_process` doesn't have `workerData` like `worker_threads` do, we'll need to include `workerId` in start up message, here:

https://github.com/tinylibs/tinypool/blob/ac2e83917557df2deff74b9b6ea0c83319f32a45/src/index.ts#L756-L762

Then process worker can read it from channel and set it into global state:

https://github.com/tinylibs/tinypool/blob/ac2e83917557df2deff74b9b6ea0c83319f32a45/src/entry/process.ts#L26

**Comment by alisd23** [comment]
Happy to look into this, thanks for the initial info @AriPerkkio 

I have a solution now which I think works, but it passes the workerId down through `process.env` instead (as `TINYPOOL_WORKER_ID`, so the ID is available to set into `process.__tinypool_state__` as soon as the entry file runs, instead of waiting for startup message.

Thoughts on this? Or is it better/cleaner to wait for the startup message then set workerId then?

**Comment by AriPerkkio** [comment]
Oh that's really clever solution - and even better than passing it in start up message, as that way it would be available immediately. Let's proceed with `process.env` approach.

**Comment by alisd23** [comment]
Nice! PR up here https://github.com/tinylibs/tinypool/pull/81

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/tinylibs/tinypool/pull/81.
