### ISSUE TITLE
Codebase question regarding isolate workers

### ISSUE THREAD

**Issue by rluvaton** [tinylibs/tinypool#90]
Great repo!

I noticed that if `isolateWorkers` is `true` you reuse the same workers (`recycle`) but wouldn't that lead to stuff being kept in the previous run of the worker?

**Comment by AriPerkkio** [comment]
When `isolateWorkers` is `true` the workers are terminated after a task has been run.

https://github.com/tinylibs/tinypool/blob/c444320e746c8ca170f82fb78b8c854e23c2078d/src/index.ts#L1015-L1024

https://github.com/tinylibs/tinypool/blob/c444320e746c8ca170f82fb78b8c854e23c2078d/src/index.ts#L917-L918

https://github.com/tinylibs/tinypool/blob/c444320e746c8ca170f82fb78b8c854e23c2078d/src/index.ts#L840-L846

https://github.com/tinylibs/tinypool/blob/c444320e746c8ca170f82fb78b8c854e23c2078d/src/index.ts#L481-L497

When isolation is disabled, then it indeed leads to a situation where worker may have side effects caused by previous run.

**Comment by rluvaton** [comment]
Thank you, I thought recycle meaning reuse
